### ISSUE TITLE
RuoYi-Vue-fast 集成mybatisplus 出现错误

### ISSUE THREAD

**Issue by jpx1024** [yangzongzhuan/RuoYi-Vue-fast#22]
我使用RuoYi-Vue-fast版本按照官网文档将mybatis换成mybatisplus，结果出现了这个问题Invalid bound statement (not found): com.ruoyi.project.system.mapper.SysConfigMapper.selectConfigList

**Comment by joychou996** [comment]
me too

**Comment by joychou996** [comment]
原因是因为官网写的xml扫描地址不对，应该是：  mapperLocations: classpath*:mybatis/**/*Mapper.xml

**Comment by yangzongzhuan** [comment]
注意扫描的包路径和地址。
