### ISSUE TITLE
页面的vue文件，必须写根标签！？

### ISSUE THREAD

**Issue by elarbor** [yangzongzhuan/RuoYi-Vue-fast#25]
vue2才必须写根标签呢，现在vue3了，还必须写根标签啊？
![动画](https://github.com/user-attachments/assets/a974f30b-1f6f-442d-8df8-13e24649caf2)

![动画](https://github.com/user-attachments/assets/49c9c51d-7a6e-495b-91e3-90f6258da252)

**Comment by yangzongzhuan** [comment]
是的呢
