### ISSUE TITLE
启动前后分离单体项目登录接口报404

### ISSUE THREAD

**Issue by fjs-fjs** [yangzongzhuan/RuoYi-Vue-fast#7]
![image](https://user-images.githubusercontent.com/57973594/119768314-024b1880-beeb-11eb-88b9-c8a2fb67221d.png)

**Comment by yangzongzhuan** [comment]
需要启动ruoyi-ui前端。
https://gitee.com/y_project/RuoYi-Vue/tree/master/ruoyi-ui
